### ISSUE TITLE
Examples with multiple Hosts?

### ISSUE THREAD

**Issue by h0ckeyst1ck** [gubertoli/ProbingDataset#1]
That's almost exactly what I'm looking for. I find the dataset very helpful!
Will you also upload examples where a whole range is scanned with multiple contacted hosts?
Thanks in advance for your answer!

**Comment by gubertoli** [comment]
Nice to hear from you @h0ckeyst1ck 

Do you mean a larger target address space? Changing the scripts on testbed/scripts does not address your needs?

If you detail your needs more, I can think about how to address it.
